### ISSUE TITLE
output

### ISSUE THREAD

**Issue by starkers** [t0mmyt/haproxystats-ruby#1]
Two requests if possible:
## sorted output

The output seems to kick out the backends in an inconsistent way, could you apply a |sort to this within the code somehow?

EG:

```
[root@web1 starkd]# while true ; do ./haproxy.rb | grep -v admin ; echo "====="  ; sleep 1 ; done
mysql 1.0
bucket1 1.0
=====
bucket1 1.0
mysql 1.0
=====
mysql 1.0
bucket1 1.0
=====
mysql 1.0
bucket1 1.0
=====
```
## values returned

Currently it returns something like this (note bucket1 has a failed backend)

```
bucket1 0.666666666666667
mysql 1.0
```

How hard is it to simply spit out the ratio? EG: the failed bucket1 BE is 1 of 3

```
bucket1 2/3
mysql 5/5
```

**Comment by t0mmyt** [comment]
Sort added to .services

The upratio is by design so you could do
`if ha.upratio(service) < 0.5 then alert "More than half of your backends is are down."`

I've added an up method so you can do
`up(service)` of `backends(service).length`
